### ISSUE TITLE
Source code please + Do you speak German ?

### ISSUE THREAD

**Issue by MineStone** [Leurak/Bonzify#1]
Hi leurak, I was just wondering when you're going to publish the source code. I understand that maybe you don't have the time, but I really want to have a look at it.
And, just for curiosity, do you speak German ? In case you do, I do as well ;)
Keep up the good work !

**Comment by kiroma** [comment]
When you enter the repository the first thing you see is "Source Code will be coming soon, because I have to improve the rushed code a lot, add disclaimers and stuff..."
Just be patient, it will come out soon.

**Comment by LoganDark** [comment]
"I understand that you can't, but I really want you to, so I'm going to complain about it"

**Comment by santanuthepro** [comment]
leurak eats memz daily
