### ISSUE TITLE
Are you dead?

### ISSUE THREAD

**Issue by Trojan7z7VZX** [Leurak/Bonzify#9]
Man! You Said you'd upload the source code "SOON" and it's been a YEAR now and you still haven't!

**Comment by DigitalJokerMan** [comment]
Yeah sadly. If you look at his gravestone it says "RIP Leurak - Death by little kids that aren't fucking patient."

Nuff said.

**Comment by MineStone** [comment]
DigitalJokerMan You do now that bonzify was created a year ago and it sais "soon" in the Readme. I honestly think leurak either forgot this thing or just don't care about it anymore. I can be patient but this is no what me and the majority of people I know call "soon"

**Comment by EricZhang456** [comment]
@MineStone I don't think he forgot it.

**Comment by ElektroKill** [comment]
He is not dead

**Comment by Leurak** [comment]
no
